artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://samsum-dataset-261106.s3.us-east-1.amazonaws.com/samsums_dataset.zip
  object_key: samsums_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  bucket_name: samsum-dataset-261106